### PR TITLE
fix(cli): changed persist format options to array

### LINKED ISSUE #95: Format options should process `md,stdout` to an array
- Figure out what is the official separator and then change it
- Look up in yargs documentation
- Split up stings based up on separator

### PR DESCRIPTION
**Pull request by MishaSeredenkoPushBased**
closes #95

### CODE REVIEW

File: packages/cli/src/lib/yargs-cli.ts [hunk 1]
```diff
@@ -81,6 +82,8 @@ export function yargsCli(
     });
   });
 
+  console.log(cli.argv);
```
Comment (BioPhoton) [inline packages/cli/src/lib/yargs-cli.ts:85]: before merge pls remove this

**Comment by MishaSeredenkoPushBased** [comment]
Tests were fixed after the console.log removal

**Review by vmasek — APPROVED** [review]

**Comment by vmasek** [comment]
Let's squash and merge this.
